name: MWMCaps
main: com.magicaldreams.madewithmagiccaps.Main
version: 0.75.9
api-version: 1.14
author: Nolant108
authors: [MagicalDreams]
website: magicaldreams.us , github.com/nolant108
commands:
  cap: